# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish_nuget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Publish
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/OpenAI.Net/OpenAI.Net.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
