name: push to nuget

on:
  push:
    branches: [ publish ]
jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./src/OpenAI.Net
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET461
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.6.1
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Package
      run: dotnet pack -c Release -p:PackageId=Hobo.OpenAI -o . OpenAI.Net.csproj
    - name: Publish
      run: dotnet nuget push Hobo.OpenAI.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
